import type { Bill } from '~/types';

// Mock data - replace with actual data storage later

const mockBills: Bill[] = [
  {
    id: '1',
    providerName: 'Fresh Farms',
    items: [
      { id: '1', name: 'Tomatoes', quantity: 10, price: 2 },
      { id: '2', name: 'Cucumbers', quantity: 5, price: 1.5 },
    ],
    total: 27.5,
    date: '2023-04-15',
    signer: 'John Doe',
    providerId: '1',
  },
  {
    id: '2',
    providerName: 'Green Gardens',
    items: [
      { id: '1', name: 'Carrots', quantity: 20, price: 1 },
      { id: '2', name: 'Lettuce', quantity: 8, price: 2.5 },
      { id: '3', name: 'Cucumbers', quantity: 5, price: 1.5 },
      { id: '4', name: 'Tomatoes', quantity: 10, price: 2 },
      { id: '5', name: 'Zucchini', quantity: 6, price: 1.75 },
      { id: '6', name: 'Green Beans', quantity: 8, price: 2.25 },
    ],
    total: 40,
    date: '2023-04-16',
    signer: 'Jane Smith',
    providerId: '2',
  },
  {
    id: '3',
    providerName: 'Sunny Farms',
    items: [
      { id: '1', name: 'Potatoes', quantity: 15, price: 1.75 },
      { id: '2', name: 'Onions', quantity: 12, price: 1.25 },
    ],
    total: 41.25,
    date: '2023-04-18',
    signer: 'Mike Johnson',
    providerId: '3',
  },
  {
    id: '4',
    providerName: 'Rainy Farms',
    items: [
      { id: '1', name: 'Bell Peppers', quantity: 8, price: 2.5 },
      { id: '2', name: 'Zucchini', quantity: 6, price: 1.75 },
    ],
    total: 30.5,
    date: '2023-04-20',
    signer: 'Sarah Wilson',
    providerId: '4',
  },
  {
    id: '5',
    providerName: 'Cloudy Farms',
    items: [
      { id: '1', name: 'Broccoli', quantity: 10, price: 2.25 },
      { id: '2', name: 'Cauliflower', quantity: 7, price: 2.75 },
    ],
    total: 41.75,
    date: '2023-04-22',
    signer: 'Tom Brown',
    providerId: '5',
  },
  {
    id: '6',
    providerName: 'Fresh Farms',
    items: [
      { id: '1', name: 'Spinach', quantity: 15, price: 1.5 },
      { id: '2', name: 'Kale', quantity: 10, price: 2 },
    ],
    total: 42.5,
    date: '2023-04-25',
    signer: 'Emily Davis',
    providerId: '1',
  },
  {
    id: '7',
    providerName: 'Green Gardens',
    items: [
      { id: '1', name: 'Mushrooms', quantity: 12, price: 3 },
      { id: '2', name: 'Green Beans', quantity: 8, price: 2.25 },
    ],
    total: 54,
    date: '2023-04-27',
    signer: 'Alex Turner',
    providerId: '2',
  },
  {
    id: '8',
    providerName: 'Sunny Farms',
    items: [
      { id: '1', name: 'Sweet Potatoes', quantity: 20, price: 1.5 },
      { id: '2', name: 'Garlic', quantity: 15, price: 1 },
    ],
    total: 45,
    date: '2023-04-29',
    signer: 'Chris Martin',
    providerId: '3',
  },
  {
    id: '9',
    providerName: 'Rainy Farms',
    items: [
      { id: '1', name: 'Asparagus', quantity: 10, price: 3.5 },
      { id: '2', name: 'Celery', quantity: 8, price: 2 },
    ],
    total: 51,
    date: '2023-05-01',
    signer: 'Lisa Anderson',
    providerId: '4',
  },
  {
    id: '10',
    providerName: 'Cloudy Farms',
    items: [
      { id: '1', name: 'Radishes', quantity: 15, price: 1.25 },
      { id: '2', name: 'Beets', quantity: 12, price: 1.75 },
    ],
    total: 39.75,
    date: '2023-05-03',
    signer: 'David Clark',
    providerId: '5',
  },
  {
    id: '11',
    providerName: 'Fresh Farms',
    items: [
      { id: '1', name: 'Cherry Tomatoes', quantity: 12, price: 2.5 },
      { id: '2', name: 'Mini Cucumbers', quantity: 10, price: 2 },
    ],
    total: 50,
    date: '2023-05-05',
    signer: 'Rachel Green',
    providerId: '1',
  },
  {
    id: '12',
    providerName: 'Green Gardens',
    items: [
      { id: '1', name: 'Romaine Lettuce', quantity: 15, price: 2 },
      { id: '2', name: 'Arugula', quantity: 10, price: 2.5 },
    ],
    total: 55,
    date: '2023-05-07',
    signer: 'Ross Geller',
    providerId: '2',
  },
  {
    id: '13',
    providerName: 'Sunny Farms',
    items: [
      { id: '1', name: 'Yellow Squash', quantity: 12, price: 1.75 },
      { id: '2', name: 'Eggplant', quantity: 8, price: 2.25 },
    ],
    total: 39,
    date: '2023-05-09',
    signer: 'Monica Bing',
    providerId: '3',
  },
  {
    id: '14',
    providerName: 'Rainy Farms',
    items: [
      { id: '1', name: 'Brussels Sprouts', quantity: 10, price: 2.75 },
      { id: '2', name: 'Artichokes', quantity: 6, price: 3.5 },
    ],
    total: 48.5,
    date: '2023-05-11',
    signer: 'Chandler Bing',
    providerId: '4',
  },
  {
    id: '15',
    providerName: 'Cloudy Farms',
    items: [
      { id: '1', name: 'Swiss Chard', quantity: 8, price: 2.25 },
      { id: '2', name: 'Collard Greens', quantity: 10, price: 2 },
    ],
    total: 38,
    date: '2023-05-13',
    signer: 'Joey Tribbiani',
    providerId: '5',
  },
  {
    id: '16',
    providerName: 'Fresh Farms',
    items: [
      { id: '1', name: 'Green Onions', quantity: 20, price: 1 },
      { id: '2', name: 'Parsley', quantity: 15, price: 1.5 },
    ],
    total: 42.5,
    date: '2023-05-15',
    signer: 'Phoebe Buffay',
    providerId: '1',
  },
  {
    id: '17',
    providerName: 'Green Gardens',
    items: [
      { id: '1', name: 'Red Cabbage', quantity: 10, price: 2.25 },
      { id: '2', name: 'Green Cabbage', quantity: 10, price: 2 },
    ],
    total: 42.5,
    date: '2023-05-17',
    signer: 'Ben Geller',
    providerId: '2',
  },
  {
    id: '18',
    providerName: 'Sunny Farms',
    items: [
      { id: '1', name: 'Snap Peas', quantity: 12, price: 2.5 },
      { id: '2', name: 'Snow Peas', quantity: 12, price: 2.25 },
    ],
    total: 57,
    date: '2023-05-19',
    signer: 'Emma Geller',
    providerId: '3',
  },
  {
    id: '19',
    providerName: 'Rainy Farms',
    items: [
      { id: '1', name: 'Turnips', quantity: 15, price: 1.75 },
      { id: '2', name: 'Rutabaga', quantity: 10, price: 2 },
    ],
    total: 46.25,
    date: '2023-05-21',
    signer: 'Gunther Smith',
    providerId: '4',
  },
  {
    id: '20',
    providerName: 'Cloudy Farms',
    items: [
      { id: '1', name: 'Leeks', quantity: 12, price: 2 },
      { id: '2', name: 'Shallots', quantity: 15, price: 1.75 },
    ],
    total: 50.25,
    date: '2023-05-23',
    signer: 'Carol Willick',
    providerId: '5',
  },
];

const Providers = [
  { id: '1', name: 'Fresh Farms' },
  { id: '2', name: 'Green Gardens' },
  { id: '3', name: 'Sunny Farms' },
  { id: '4', name: 'Rainy Farms' },
  { id: '5', name: 'Cloudy Farms' },
];

export { mockBills, Providers };
